services:
  mysql:
    container_name: 'guide-mysql'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=Blaziken321'
      - 'MYSQL_ROOT_PASSWORD=Blaziken321'
      - 'MYSQL_USER=root'
    ports:
      - '3306:3306'